# Generated by Django 5.1.3 on 2025-01-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0003_alter_shippingaddress_shipping_address2_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_shipped",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped",
            field=models.BooleanField(default=False),
        ),
    ]
